language: node_js
node_js:
- '4'
- '5'
deploy:
  provider: npm
  email: csaba.tuncsik@gmail.com
  api_key:
    secure: pd/51U/2SjJY9M0Nr80HqQ1M8vFmmG+h6NdFo2FYLFPIzny9IOg5ceI1Yl3HHo1y88fCR1SwcfsVlrBsMlqQfXpS6jepSGcO8is15SXBQb4Z1zlDPWdr2MSqDpxZfwgbiMWvdYDgwuFRdBPsqYpQi/zBXDyhnxyx5dIsC48csQNFel3leZLmt8ajZO17p1e9543QqNAKvsGUROgShLjoHEMqqVD6EYJONegm0aWmMBPKeVG3VNXvfi6ES+rWv9JdPfpmrbp/+MXsBFSYQtejIAVRUNTyqGuOvVKS8J0wAWBwutWE+HzLfXCkUQ39jOoGLb5iYWONTEb9IqH/4MotRF3O7i9jdJ01q+AYXZ4nE1g3k+gGmCbmxPEpOkIgcJUSHbAJyTngo/VOltQWlqUmvs3EeTA+nutTEZi/nAMhBP//R0Ka1J6G8+5/P39c+KmIFfmwOqTqTp9AOcAn5pGav79gcaZJ2VJbo8E7fOIO2RRJB65kkventkekGPHbJw4wR2B3PCb93Nlh5vQHDFUtrQlZBLae4GbT47RrnoihxhDFc/FGWsyVOEHIcR9K9U2daF/dBdonP6Vm1UCJDgwqAilkuHzWCuy+eKDt1MszrpoTazKRymHu/d2ctCDYek5wy4AmAcmJbWY4sCus09B1th7dcr6adbTd9T6fRc/bHo8=
  on:
    tags: true
    all_branches: true
    repo: cstuncsik/es6-node-module-boilerplate
  skip_cleanup: true
